/* SimParam.h Simulation Parameters */
#ifndef SIMULATION_PARAMETERS_H
#define SIMULATION_PARAMETERS_H

#define NUM_EVENT_GENERATORS 1
#define NUM_EVENTS_PER_GEN 50
#define NUM_EVENT_HANDLERS 1
#define TOTAL_NUM_EVENTS (NUM_EVENTS_PER_GEN) * (NUM_EVENT_GENERATORS)
	
#define CIR_QUEUE_CAPACITY 10
#define MAX_ROUND 1000

#endif